{% set version = "1.0.0" %}

package:
  name: grass
  version: {{ version }}

source:
  git_url: https://github.com/OSGeo/grass.git
  # path: /home/hcho/usr/grass/grass
  # path: C:/opt/grass

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make  # [unix]
  host:
    - proj
    - fftw
    - openblas
    - pdal
    - wxpython
    - flex  # [unix]
    - bison # [unix]
    - gdal  # [unix]
    - xorg-libx11  # [unix]
    - xorg-xproto  # [unix]
    - libopengl # [unix]
    - libgl-devel  # [unix]
    - cairo # [unix]
    - postgresql  # [unix]
    - gettext  # [unix]
    - libglu  # [unix]
    - winflexbison # [win]
    - libgdal  # [win]
    - pcre # [win]
    - pywin32 # [win]
  run:
    - proj
    - fftw
    - openblas
    - pdal
    - wxpython
    - flex  # [unix]
    - bison # [unix]
    - gdal  # [unix]
    - xorg-libx11  # [unix]
    - xorg-xproto  # [unix]
    - libopengl # [unix]
    - libgl-devel  # [unix]
    - cairo # [unix]
    - postgresql  # [unix]
    - gettext  # [unix]
    - libglu  # [unix]
    - winflexbison # [win]
    - libgdal  # [win]
    - pcre # [win]
    - pywin32 # [win]

about:
  home: https://grass.osgeo.org/
  license: GPL 2+
  summary: GRASS (https://grass.osgeo.org/) is a Geographic Information System used for geospatial data management and analysis, image processing, graphics/map production, spatial modeling, and visualization.
  dev_url: https://github.com/OSGeo/grass
  doc_url: https://grass.osgeo.org/grass-stable/manuals/index.html
