{% set version = "1.0.0" %}

package:
  name: grass
  version: {{ version }}

source:
  git_url: https://github.com/OSGeo/grass.git
#  path: /home/hcho/usr/grass/grass

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make # [unix]
    - pkg-config
    #- msbuild # [win]
  host:
    - flex
    - bison
    - proj
    - gdal
    - xorg-libx11
    - xorg-xproto
    - libopengl
    - libgl-devel
    - cairo
    - postgresql
    - gettext
    - fftw
    - openblas
    - pdal
    - libglu
    - wxpython
  run:
    - flex
    - bison
    - proj
    - gdal
    - xorg-libx11
    - xorg-xproto
    - libopengl
    - libgl-devel
    - cairo
    - postgresql
    - gettext
    - fftw
    - openblas
    - pdal
    - libglu
    - wxpython

about:
  home: https://grass.osgeo.org/
  license: GPL 2+
  summary: GRASS (https://grass.osgeo.org/) is a Geographic Information System used for geospatial data management and analysis, image processing, graphics/map production, spatial modeling, and visualization.
  dev_url: https://github.com/OSGeo/grass
  doc_url: https://grass.osgeo.org/grass-stable/manuals/index.html
