{% set version = "1.0.0" %}

package:
  name: grass
  version: {{ version }}

source:
  url: file:///home/kandeln/grass.zip

build:
  number: 0

requiements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - proj
    - libgdal
    - fftw
    - blas
    - libpdal
    - wxPython

about:
  home: https://grass.osgeo.org/
  license: 'GNU General Public License'
  summary: 'GRASS GIS (https://grass.osgeo.org/) is a Geographic Information System used for geospatial data management and analysis, image processing, graphics/map production, spatial modeling, and visualization.'
  dev_url: https://github.com/OSGeo/grass
  doc_url: https://grass.osgeo.org/learn/manuals/

extra:
  recipe-maintainers:
    - grass


