{% set version = "8.4.2" %}
{% set sha256 = "68abc6c119939e40736a96360e9f6ab73e56f74772ec88c31688136215047a8c" %}

package:
  name: grass
  version: {{ version }}

source:
  url: https://github.com/OSGeo/grass/releases/download/{{ version }}/grass-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}      # [unix]
    - bison          # [unix]
    - flex           # [unix]
    - gcc            # [win]
    - gettext-tools
    - m2-bash        # [win]
    - m2-bison       # [win]
    - m2-coreutils   # [win]
    - m2-flex        # [win]
    - m2-grep        # [win]
    - m2-sed         # [win]
    - make           # [unix]
    - pkg-config
    - sed            # [unix]
  host:
    - bzip2
    - cairo
    - expat
    - fftw
    - fontconfig
    - freetype
    - gettext       # [osx]
    - libgdal-core
    - libgl-devel   # [linux]
    - libglu        # [linux]
    - libgomp       # [linux]
    - libiconv
    - libopenblas
    - libpdal-core
    - libpng
    - libpq
    - libsqlite
    - libtiff
    - llvm-openmp   # [osx]
    - pcre          # [win]
    - proj
    - python
    - readline      # [unix]
    - wxpython
    - xorg-libx11   # [linux]
    - zlib
    - zstd
  run:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - python
    - wxpython

test:
  commands:
    - grass --version

about:
  home: https://grass.osgeo.org/
  summary: GRASS computational engine for raster, vector, and geospatial processing
  description: |
    GRASS is a geospatial engine that enables spatial data analysis,
    visualization, and modeling. It provides researchers and practitioners with
    science-backed tools to understand and manage landscapes, natural
    resources, and human environments.
  license: GPL-2.0-or-later
  license_file: COPYING
  doc_url: https://grass.osgeo.org/grass-stable/manuals/
  dev_url: https://github.com/OSGeo/grass

extra:
  recipe-maintainers:
    - HuidaeCho
    - wenzeslaus
