{% set version = "dev" %}

package:
  name: grass
  version: {{ version }}

source:
  git_url: https://github.com/OSGeo/grass.git

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - bison
    - cmake
    - flex
    - gettext-tools
    - make           # [unix]
    - pkg-config
  host:
    - bzip2
    - cairo
    - expat
    - fftw
    - fontconfig
    - freetype
    - gettext       # [osx]
    - libgdal-core
    - libgl-devel   # [linux]
    - libglu        # [linux]
    - libiconv
    - libpdal-core
    - libpng
    - libpq
    - libsqlite
    - libtiff
    - openblas
    - proj
    - python
    - readline
    - wxpython
    - xorg-libx11   # [linux]
    - zlib
    - zstd
  run:
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]
    - python
    - wxpython

about:
  home: https://grass.osgeo.org/
  summary: GRASS computational engine for raster, vector, and geospatial processing
  description: |
    GRASS is a geospatial engine that enables spatial data analysis,
    visualization, and modeling. It provides researchers and practitioners with
    science-backed tools to understand and manage landscapes, natural
    resources, and human environments.
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  doc_url: https://grass.osgeo.org/grass-stable/manuals/
  dev_url: https://github.com/OSGeo/grass

extra:
  recipe-maintainers:
    - HuidaeCho
