{% set version = "dev" %}

package:
  name: grass
  version: {{ version }}

source:
  git_url: https://github.com/OSGeo/grass.git

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}      # [unix]
    - bison          # [unix]
    - cmake
    - flex           # [unix]
    - gettext-tools
    - m2-bison       # [win]
    - m2-flex        # [win]
    - make           # [unix]
    - pkg-config
  host:
    - bzip2
    - cairo
    - fftw
    - fontconfig
    - freetype
    - gettext       # [osx]
    - libgdal-core
    - libgl-devel   # [linux]
    - libglu        # [linux]
    - libgomp       # [linux]
    - libiconv
    - libpdal-core
    - libpng
    - libpq
    - libsqlite
    - libtiff
    - llvm-openmp   # [osx]
    - openblas
    - pcre          # [win]
    - proj
    - python
    - pywin32       # [win]
    - readline      # [unix]
    - wxpython
    - xorg-libx11   # [linux]
    - zlib
    - zstd
  run:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - python
    - wxpython

test:
  commands:
    - grass --version

about:
  home: https://grass.osgeo.org/
  summary: GRASS computational engine for raster, vector, and geospatial processing
  description: |
    GRASS is a geospatial engine that enables spatial data analysis,
    visualization, and modeling. It provides researchers and practitioners with
    science-backed tools to understand and manage landscapes, natural
    resources, and human environments.
  license: GPL-2.0-or-later
  license_file: COPYING
  doc_url: https://grass.osgeo.org/grass-stable/manuals/
  dev_url: https://github.com/OSGeo/grass

extra:
  recipe-maintainers:
    - HuidaeCho
    - wenzeslaus
